spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: file:\\\E:\OneDrive\DOCUMENTOS PERSONALES\CODES\PROYECTO PORTAFOLIO\Microservicios-springCloud-CalculosExportacionPetrole\config

server:
  port: 8888


